-- Migration 009 Seed Admin (SECURITY HARDENED)
-- BUG-003: Hardcoded bcrypt hash removed from source code.
-- Admin account is now created via the initialize-admin CLI tool or env-based seeding,
-- NOT via a migration with an embedded password hash.
--
-- To create the initial admin account, run:
--   cd backend && go run cmd/initialize_admin/main.go
-- This reads ADMIN_USERNAME, ADMIN_PASSWORD, ADMIN_EMAIL from environment variables.
--
-- This file intentionally left as a no-op to avoid re-executing old unsafe seed.
SELECT 1; -- no-op placeholder
